"use client"
import Head from "next/head";
import { NextPage } from "next";
import { useEffect, useState } from "react";
import styles from "./Styles/Home.module.css"
import { MoonLoader } from "react-spinners";
const axios = require('axios');

export default function Home() {

    const [suggestion, setSuggestion] = useState('')
    const [loading, setLoading] = useState(false)
  
    
  
    const submit = async () => {
      // Check if character limit is exceeded
      

        const options = {
          method: 'GET',
          url: 'https://jokes-by-api-ninjas.p.rapidapi.com/v1/jokes',
          headers: {
            'X-RapidAPI-Key': 'b77bdcdc5bmsha6a2817bc9c650fp1b8f20jsn6b8c5743adc0',
            'X-RapidAPI-Host': 'jokes-by-api-ninjas.p.rapidapi.com'
          }
        };
  
      // Set loading state
      setLoading(true)
  
      try {
        const res = await axios.request(options);

        console.log(res.data);  
        if (Array.isArray(res.data) && res.data.length > 0 && res.data[0].joke) {
          const result = res.data[0].joke;
          setSuggestion(result);
        }
      } catch (error) {
        console.log(error)
      } finally {
        setLoading(false)
      }
    }
  return (
    <div className={styles.container}>
      <Head>
        <title>Joke based on Your Mood</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='max-w-7xl mx-auto py-12'>
        <h2 className='text-2xl font-b  old text-center pb-2'>Joke based on Your Mood</h2>
        {/* Input field for marketing copy */}
        <div className='flex flex-col gap-4 justify-center w-1/3 mx-auto'>
          
          <button
            type='button'
            onClick={submit}
            className='bg-blue-500 h-12 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'>
            {loading ? (
              <div className='flex justify-center items-center gap-4'>
                <p>Loading...</p>
                <MoonLoader size={20} color='white' />
              </div>
            ) : (
              'Generate'
            )}
          </button>

          {/* Output field for marketing copy */}
          {suggestion && (
            <div className='mt-8'>
              <h4 className='text-lg font-semibold pb-2'>Your Joke:</h4>
              <div className='relative w-full rounded-md bg-gray-100 p-4'>
                <p className='text-sm text-gray-700'>{suggestion}</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
